image: node:16.14.0

<<<<<<< HEAD
# default:
#   before_script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - apt-get install -u zip unzip
#     - gem install dpl

=======
>>>>>>> 4f46e01f (Update .gitlab-ci.yml)
cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy_uat
  - deploy_frontend_prod
  - deploy_backend_prod
  - sonarqube-check

build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - cd codeanalyzer-backend
    # - npm install

test:
  stage: test
  script:
    - echo "Pipeline test started"
  tags:
    - dalfcs_gitlab_docker_ci

deploy_uat:
  stage: deploy_uat
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - echo "dbURL=$DATABASE_TEST_URL" >> .env
    - echo "dbUserName=$DATABASE_TEST_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_TEST_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the develop pipeline"
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - git clone https://git.cs.dal.ca/courses/2022-winter/csci-5308/group4.git
    - git checkout uat
    - cd group4
    - yarn
  only:
    - uat

<<<<<<< HEAD
sonarqube-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - qurram # or the name of your main branch

<<<<<<< HEAD
deploy_prod:
  stage: deploy_prod
<<<<<<< HEAD
<<<<<<< HEAD
=======
deploy_backend_prod:
<<<<<<< HEAD
  stage: deploy_backend_prod
>>>>>>> 64da8f70 (Update .gitlab-ci.yml)
=======
  stage: deploy_prod
>>>>>>> 8e4ae227 (fixing yaml)
=======
  skip_cleanup: true
>>>>>>> 70bb52fb (setting skip_cleanup)
=======
>>>>>>> ddc2f904 (updating node version)
=======
deploy_backend_prod:
  stage: deploy_backend_prod
>>>>>>> 1dc92b68 (removing datetime)
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - apt-get install -u zip unzip
    - gem install faraday -v 1.10.0
    - gem install dpl
<<<<<<< HEAD
<<<<<<< HEAD
    - cd codeanalyzer-backend
<<<<<<< HEAD
=======
    - cd code-analyzer-backend
>>>>>>> ddc2f904 (updating node version)
=======
    - npm config set legacy-peer-deps true
    - cd codeanalyzer-backend
>>>>>>> de9fe714 (node dependency fix)
    - echo "DATABASE_HOST=$DATABASE_PROD_HOST" > .env
    - echo "DATABASE_PORT=$DATABASE_PROD_PORT" > .env
    - echo "DATABASE_NAME=$DATABASE_PROD_NAME" > .env
    - echo "DATABASE_USERNAME=$DATABASE_PROD_USERNAME" >> .env
    - echo "DATABASE_PASSWORD=$DATABASE_PROD_PASSWORD" >> .env
#    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the release pipeline"
<<<<<<< HEAD
<<<<<<< HEAD
    - chmod og-rwx ${DEPLOY_PROD_SSH_KEY}
=======
>>>>>>> 821627c9 (fixing yaml)
    - dpl --provider=heroku --app=$HEROKU_APP_BACKEND --api-key=$HEROKU_API_KEY
=======
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
>>>>>>> d5f1a8a8 (removing unnecessary permissions)
  only:
    - main
=======
    - echo "dbURL=$DATABASE_PROD_URL" > .env
    - echo "dbUserName=$DATABASE_PROD_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_PROD_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the backend release pipeline"
    - dpl --provider=heroku --app=$HEROKU_BACKEND_APP --api-key=$HEROKU_BACKEND_API_KEY

deploy_frontend_prod:
  stage: deploy_frontend_prod
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - apt-get install -u zip unzip
    - gem install faraday -v 1.10.0
    - gem install dpl
    - npm config set legacy-peer-deps true
    - cd codeanalyzer-frontend
    - echo "Deploying the frontend release pipeline"
<<<<<<< HEAD
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
<<<<<<< HEAD

only:
  - main
>>>>>>> 64da8f70 (Update .gitlab-ci.yml)
=======
=======
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY --skip-cleanup
>>>>>>> 3f7d437c (fixing uml typo)
  only:
    - main
>>>>>>> f889e6db (fixing yaml)
