image: node:latest

# trigger:
#   branches:
#     include:
#       - uat
#   paths:
#     include:
#       - codeanalyzer-backend
#       - node_modules/

default:
  before_script:
    - cloud-init status --wait
    - sudo apt-get update
    - sudo apt-get install -y zip unzip

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - cd codeanalyzer-backend
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - echo "Pipeline test started"
  tags:
    - dalfcs_gitlab_docker_ci

deploy_develop:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - apt-get install zip unzip
    - echo "dbURL=$DATABASE_TEST_URL" >> .env
    - echo "dbUserName=$DATABASE_TEST_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_TEST_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the develop pipeline"
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip codeanalyzer-backend
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip"
  only:
    - uat

deploy_release:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  artifacts:
    paths:
      - node_modules
  script:
    - cd codeanalyzer-backend
    - echo "dbURL=$DATABASE_PROD_URL" > .env
    - echo "dbUserName=$DATABASE_PROD_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_PROD_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the release pipeline"
    - chmod og-rwx ${DEPLOY_PROD_SSH_KEY}
    - git clone -b main https://git.cs.dal.ca/courses/2022-winter/csci-5308/group4.git
  only:
    - main
