image: node:16.14.0

# trigger:
#   branches:
#     include:
#       - uat
#   paths:
#     include:
#       - codeanalyzer-backend
#       - node_modules/

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - ugrad
  script:
    - cd codeanalyzer-backend
    - yarn
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - echo "Pipeline test started"
  tags:
    - ugrad

deploy_develop:
  stage: deploy
  tags:
    - ugrad
  script:
    - echo "dbURL=$DATABASE_TEST_URL" >> .env
    - echo "dbUserName=$DATABASE_TEST_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_TEST_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the develop pipeline"
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" codeanalyzer-backend "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-codeanalyzer-backend"
  only:
    - dev

deploy_release:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - node_modules
  script:
    - cd codeanalyzer-backend
    - echo "dbURL=$DATABASE_PROD_URL" > .env
    - echo "dbUserName=$DATABASE_PROD_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_PROD_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the release pipeline"
    - chmod og-rwx ${DEPLOY_PROD_SSH_KEY}
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" codeanalyzer-backend "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-codeanalyzer-backend"
  only:
    - main
