image: node:latest

default:
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - apt-get install -u zip unzip
    - gem install dpl

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy_uat
  - deploy_prod

build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - cd codeanalyzer-backend
    - npm install

test:
  stage: test
  script:
    - echo "Pipeline test started"
  tags:
    - dalfcs_gitlab_docker_ci

deploy_uat:
  stage: deploy_uat
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - apt-get install zip unzip
    - echo "dbURL=$DATABASE_TEST_URL" >> .env
    - echo "dbUserName=$DATABASE_TEST_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_TEST_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the develop pipeline"
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip codeanalyzer-backend
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.zip"
  only:
    - uat

deploy_prod:
  stage: deploy_prod
  script:
    - cd codeanalyzer-backend
    - echo "dbURL=$DATABASE_PROD_URL" > .env
    - echo "dbUserName=$DATABASE_PROD_USERNAME" >> .env
    - echo "dbPassword=$DATABASE_PROD_PASSWORD" >> .env
    - echo "dbDriver=$DATABASE_DRIVER" >> .env
    - echo "Deploying the release pipeline"
    - chmod og-rwx ${DEPLOY_PROD_SSH_KEY}
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - main
